### ISSUE TITLE
TypeError: user() missing 1 required positional argument: 'username'

### ISSUE THREAD

**Issue by ticki** [barosl/homu#131]
I get following error, after trying to deploy Homu in a Python virtualenv:

``` python
Traceback (most recent call last):
  File "/usr/local/bin/homu", line 9, in <module>
    load_entry_point('homu==0.2.0', 'console_scripts', 'homu')()
  File "/usr/local/lib/python3.4/dist-packages/homu-0.2.0-py3.4.egg/homu/main.py", line 870, in main
    user = gh.user()
TypeError: user() missing 1 required positional argument: 'username'
```

**Comment by sigmavirus24** [comment]
@Ticki what version of github3.py do you have installed? Also, how are you deploying Homu? (e.g., pip, setup.py install, something else)

**Comment by ticki** [comment]
> what version of github3.py do you have installed? 

That latest one. It was installed only a few hours ago.

> Also, how are you deploying Homu? (e.g., pip, setup.py install, something else)

I use the development version through setup.py (python3).

**Comment by sigmavirus24** [comment]
> That latest one. It was installed only a few hours ago.

That is not an answer. What's the version string?

> I use the development version through setup.py (python3).

As in `python setup.py install` or `python setup.py develop`. There's a difference between the two commands and the exact command is important.

**Comment by sigmavirus24** [comment]
Also, the version string for github3.py can be obtained by doing `python -c 'import github3; print(github3.__version__)'`

**Comment by ticki** [comment]
> That is not an answer. What's the version string?

Sorry, I'm not very familiar with python:

```
~> python -c 'import github3; print(github3.__version__)'
0.9.5
```

>  As in python setup.py install or python setup.py develop. There's a difference between the two commands and the exact command is important.

I used `python setup.py install`.

**Comment by sigmavirus24** [comment]
Hm. That's surprising. That exception is something I'd expect from github3.py 1.0.*

**Comment by ashcrow** [comment]
@Ticki If you installed from a source checkout (IE: git clone) can you also provide the hash? You can snag it with `git rev-parse HEAD`.

**Comment by ticki** [comment]
2104e4b154d2fba15d515b478a5bd6105c1522f6

**Comment by ashcrow** [comment]
I can reproduce this when using python 3 in the lastest HEAD.
