### ISSUE TITLE
Homu server attempts to listen on blank host

### ISSUE THREAD

**Issue by ageis** [barosl/homu#153]
The offending code is in server.py on line 465: `run(host='', port=cfg['web']['port'], server='waitress'`

Full traceback:

```
homu@ci:~$ ./venv/bin/homu -v
Retrieving pull requests...

Done!
Bottle v0.12.9 server starting up (using WaitressServer())...
Listening on http://:54856/
Hit Ctrl-C to quit.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/homu/venv/lib/python3.4/site-packages/waitress/adjustments.py", line 258, in __init__
    socket.AI_PASSIVE
  File "/usr/lib/python3.4/socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/homu/venv/lib/python3.4/site-packages/homu/server.py", line 465, in start
    run(host='', port=cfg['web']['port'], server='waitress')
  File "/home/homu/venv/bin/bottle.py", line 3117, in run
    server.run(app)
  File "/home/homu/venv/bin/bottle.py", line 2803, in run
    serve(handler, host=self.host, port=self.port)
  File "/home/homu/venv/lib/python3.4/site-packages/waitress/__init__.py", line 11, in serve
    server = _server(app, **kw)
  File "/home/homu/venv/lib/python3.4/site-packages/waitress/server.py", line 44, in create_server
    adj = Adjustments(**kw)
  File "/home/homu/venv/lib/python3.4/site-packages/waitress/adjustments.py", line 278, in __init__
    raise ValueError('Invalid host/port specified.')
ValueError: Invalid host/port specified.

^CException ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.4/threading.py", line 1060, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.4/threading.py", line 1076, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
```

**Comment by ageis** [comment]
This only affects the pip version on PyPI. There is a divergence from development in general, including database schema. Do you plan to cut a new release soon?
