### ISSUE TITLE
KeyError: 1112

### ISSUE THREAD

**Issue by alexcrichton** [barosl/homu#19]
```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41584)
Traceback (most recent call last):
  File "/usr/lib/python3.4/socketserver.py", line 609, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.4/socketserver.py", line 665, in __init__
    self.handle()
  File "/usr/lib/python3.4/http/server.py", line 398, in handle
    self.handle_one_request()
  File "/usr/lib/python3.4/http/server.py", line 386, in handle_one_request
    method()
  File "/home/rustbuild/homu/server.py", line 240, in do_POST
    self.server.states[repo_name][pull_num],
KeyError: 1112
----------------------------------------
```

For cargo [this is an issue](https://github.com/rust-lang/cargo/issues/1112).

I ended up turning on "Issue Comments" for payloads sent to homu as I wasn't seeing a payload getting sent when I wrote `@bors: retry`. Are one of the other events specifically limited to PR comments?

**Comment by alexcrichton** [comment]
I just saw this happen again, and it was as you expected, happened as a result of a comment on a closed PR. I also double checked our enabled webhook events and they're the same as what you listed.

**Comment by barosl** [comment]
It must be my comment. :smile:

It seems that comments on a closed PR will be pretty common, so now I believe those exceptions should just be silenced. I will reopen this issue to track the required change.
